### ISSUE TITLE
App crashes when I try to show/hide faster.

### ISSUE THREAD

**Issue by mixo44** [nicolaschengdev/WYPopoverController#174]
-[WYPopoverController positionPopover:](2518) : popoverContainerView.frame = {{10, 58}, {355, 599}}
2016-01-25 13:16:32.971 PTO[5396:2144757] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x156f4a9c0 of class HelpPopoverViewController was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x156f55ff0> (
<NSKeyValueObservance 0x156f7a2c0: Observer: 0x156e43d40, Key path: preferredContentSize, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x156da5d10>
)'
**\* First throw call stack:
(0x180a61900 0x1800cff80 0x180a61848 0x1813a35c0 0x10012f9cc 0x10012d1f4 0x1805118e8 0x10012d594 0x1805118e8 0x185a66248 0x1800ceb54 0x1800da080 0x1800da0e0 0x18095090c 0x1800e9ae8 0x18094542c 0x180a16a20 0x180945680 0x181e54088 0x1857bcd90 0x1000419ac 0x1804e68b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by woodydaniel** [comment]
getting the same crash. Has anyone found a solution?

**Comment by SebastienMichoy** [comment]
I just fixed this issue in the pull request #177.

**Comment by vitalys** [comment]
@SebastienMichoy This repository is abandoned, so your PR won't be merged.
Try this fork: https://github.com/sammcewan/WYPopoverController

**Comment by prathibha-sundresh** [comment]
When are u fixing this issue

**Comment by SebastienMichoy** [comment]
@prathibha-sundresh This issue has been fixed in this repository : https://github.com/sammcewan/WYPopoverController.

**Comment by ItsMyLifeDude** [comment]
@SebastienMichoy  it does not fixed am also having problem when opened and closed fast it crashes (Am USing it in swift) Error:libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by SebastienMichoy** [comment]
@ItsMyLifeDude What repository are you using? This one, or its fork https://github.com/sammcewan/WYPopoverController?
